# Use the official Node.js 18 as a parent image
FROM node:18

# Set the working directory to where your server directory will be in the container
WORKDIR /usr/src/app/server

# Copy package.json and package-lock.json from your server directory to the container
COPY server/package*.json ./
COPY src/config.js ./

# Install dependencies
RUN npm install

# Copy the rest of your application code from your server directory to the container
COPY server/ .

# Expose the port the app runs on
EXPOSE 4021

# Command to run your app
CMD ["node", "server.js"]
